### PR TITLE
update xmpp4r gem

### LINKED ISSUE #2: XMPP Input/Output: Chinese characters crashes Logstash
I have an XMPP chat that I use as input for logstash (1.4.2). When I tried to write Chinese characters in the chat, Logstash crashes quitely.

**_Command (Logstash.1.4.2)**_

<pre>bin/logstash agent --debug -vf logstash-simple.conf</pre>

**_Value input to chat (sorry forgot half ~~)**_

<pre>...怎么样?</pre>

**_longstash-simple.conf**_

<pre>
input {
  xmpp {
    password => "help!"
    rooms => ["rat-help@xxx.se/rat-helperman"]
    type => "a"
    user => "wrat-helper6@xxx.se"
  }
}

output {
  # Print each event to stdout.
  stdout {
    # Enabling 'rubydebug' codec on the stdout output will make logstash
    # pretty-print the entire event as something similar to a JSON representation.
    codec => rubydebug
  }
}
</pre>

**_Error message**_

<pre>
[2014-07-14T20:21:22.767000 #618] DEBUG -- : PROCESSING:
    <message from='rat-help@xxx.se/ewamagn' id='purple4693fe19' to='rat-helper6@xxx.se/17619225971405362081261216' type='groupchat' xmlns='jabber:client'><body>:beer::kiss:=-O:-/8-)</body><delay from='ewamagn@xxx.se/2369011202140532998212129' stamp='2014-07-14T18:12:47Z' xmlns='urn:xmpp:delay'/><x stamp='20140714T18:12:47' xmlns='jabber:x:delay'/></message> (Jabber::Message)
D, [2014-07-14T20:21:22.768000 #618] DEBUG -- : TRYING stanzacbs...
D, [2014-07-14T20:21:22.769000 #618] DEBUG -- : TRYING message/iq/presence/cbs...
output received {:event=>{"message"=>":beer::kiss:=-O:-/8-)", "@version"=>"1", "@timestamp"=>"2014-07-14T18:21:22.780Z", "type"=>"a", "room"=>"rat-help@xxx/rat-helperman", "from"=>"ewamagn"}, :level=>:debug, :file=>"(eval)", :line=>"16"}
W, [2014-07-14T20:21:22.792000 #618]  WARN -- : EXCEPTION:
    REXML::ParseException
    #<Encoding::CompatibilityError: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)>
    org/jruby/RubyRegexp.java:1697:in `match'
    file:/home/ewamagn/programming/search/logstash2/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/1.9/rexml/source.rb:210:in `match'
    file:/home/ewamagn/programming/search/logstash2/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/1.9/rexml/parsers/baseparser.rb:419:in `pull_event'
    file:/home/ewamagn/programming/search/logstash2/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/1.9/rexml/parsers/baseparser.rb:183:in `pull'
    file:/home/ewamagn/programming/search/logstash2/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/1.9/rexml/parsers/sax2parser.rb:92:in `parse'
    /home/ewamagn/programming/search/logstash2/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/xmpp4r-0.5/lib/xmpp4r/streamparser.rb:79:in `parse'
    /home/ewamagn/programming/search/logstash2/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/xmpp4r-0.5/lib/xmpp4r/stream.rb:75:in `start'
    ...
    Exception parsing
    Line: 
    Position: 0
    Last 80 unconsumed characters:
    ä¸¬å½çæ±å¬ï¼æä¹æ •?</body>
    file:/home/ewamagn/programming/search/logstash2/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/1.9/rexml/parsers/baseparser.rb:435:in `pull_event'
    file:/home/ewamagn/programming/search/logstash2/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/1.9/rexml/parsers/baseparser.rb:183:in `pull'
    file:/home/ewamagn/programming/search/logstash2/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/1.9/rexml/parsers/sax2parser.rb:92:in `parse'
    /home/ewamagn/programming/search/logstash2/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/xmpp4r-0.5/lib/xmpp4r/streamparser.rb:79:in `parse'
    /home/ewamagn/programming/search/logstash2/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/xmpp4r-0.5/lib/xmpp4r/stream.rb:75:in `start'
{
       "message" => ":beer::kiss:=-O:-/8-)",
      "@version" => "1",
    "@timestamp" => "2014-07-14T18:21:22.780Z",
          "type" => "a",
          "room" => "rat-help@xxx.se/rat-helperman",
          "from" => "ewamagn"
}
W, [2014-07-14T20:21:23.260000 #618]  WARN -- : EXCEPTION:
    TypeError
    can't convert REXML::ParseException into String
    org/jruby/RubyString.java:1159:in `+'
    /home/ewamagn/programming/search/logstash2/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/xmpp4r-0.5/lib/xmpp4r/stream.rb:136:in `parse_failure'
    /home/ewamagn/programming/search/logstash2/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/xmpp4r-0.5/lib/xmpp4r/streamparser.rb:81:in `parse'
    /home/ewamagn/programming/search/logstash2/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/xmpp4r-0.5/lib/xmpp4r/stream.rb:75:in `start'
W, [2014-07-14T20:21:23.261000 #618]  WARN -- : Exception caught in Parser thread! (TypeError)
    org/jruby/RubyString.java:1159:in `+'
    /home/ewamagn/programming/search/logstash2/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/xmpp4r-0.5/lib/xmpp4r/stream.rb:136:in `parse_failure'
    /home/ewamagn/programming/search/logstash2/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/xmpp4r-0.5/lib/xmpp4r/streamparser.rb:81:in `parse'
    /home/ewamagn/programming/search/logstash2/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/xmpp4r-0.5/lib/xmpp4r/stream.rb:75:in `start'

</pre>

### PR DESCRIPTION
**Pull request by sammcj**
Fixes #2 and other bugs caused by non-UTF8 passing errors.

Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by sammcj** [comment]
Note: Can't sign that contributor agreement as it uses some dreadful adobe plugin, even after enabling 3rd party cookies from any site as it requires you to do the buttons on the form don't seem to work.

**Comment by sammcj** [comment]
CLA signed - that Adobe system is pretty dreadful though, it doesn't work in Firefox and it requires enabling _all_ cookies from 3rd party websites...

**Comment by sammcj** [comment]
@jsvd - can we get this merged or fixed?

**Comment by sammcj** [comment]
Thanks for the merge - we noticed however that the gem hasn't been updated on rubygems - is there anything I can do to help that happen or is there something I've missed that should trigger this to be updated?

https://rubygems.org/gems/logstash-output-xmpp

**Comment by alexizmailov** [comment]
Hi guys

It's great that this fix was accepted but no one can use it as the actual gem version is 3.0.2 and it hasn't been updated yet on rubygems.org.

**Comment by guyboertje** [comment]
@sammcj @alexizmailov 
It is published now.

**Pull request merged**
